### ISSUE TITLE
Please rename to align NPM package name bmp085-sensor

### ISSUE THREAD

**Issue by rzr** [dbridges/bmp085-sensor#3]
Please rename to align NPM package name bmp085-sensor
to avoid confusion with:

* https://www.npmjs.com/package/bmp085
* https://github.com/fiskeben/bmp085

* https://www.npmjs.com/package/bmp085-sensor
* https://github.com/dbridges/bmp085

**Comment by rzr** [comment]
Ping @dbridges

**Comment by rzr** [comment]
Is this project orphaned ?

**Comment by dbridges** [comment]
Renamed.
